-- DROPPING TABLE --
DROP TABLE totalscore;
DROP TABLE login;
DROP TABLE submission;
DROP TABLE problem;
DROP TABLE contestant;

create table contestant (
  name_code VARCHAR(10) PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  school VARCHAR(50) NOT NULL
);

create table login (
  username VARCHAR(15) PRIMARY KEY,
  password VARCHAR(10),
  name_code VARCHAR(10) CONSTRAINT lg_nmc_fk REFERENCES contestant(name_code) ON DELETE CASCADE
);

CREATE TABLE problem (
  prob_num INT PRIMARY KEY,
  solution_query VARCHAR2(255)
);

CREATE TABLE submission (
  sub_id VARCHAR(11) PRIMARY KEY,
  name_code VARCHAR(10) CONSTRAINT subm_nmc_fk REFERENCES contestant(name_code) ON DELETE CASCADE ,
  submitted_text VARCHAR2(4000) NOT NULL,
  prob_num INT NOT NULL CONSTRAINT subm_submtd_fk REFERENCES problem(prob_num),
  status INT NOT NULL, 
  submit_time TIMESTAMP NOT NULL
);

CREATE TABLE scoreboard (
  name_code PRIMARY KEY CONSTRAINT tots_nc_fk REFERENCES contestant(name_code) ON DELETE CASCADE,
  prob_num INT PRIMARY KEY,
  submit_count INT,
  time INT, 
  verdict INT NOT NULL
);
--time in MINUTES--

--SELECT t.username FROM DBA_USERS t WHERE t.username LIKE 's%';
drop USER sqluntar001;
INSERT INTO contestant (name_code, name, school) VALUES ('sql-01', 'blashh21', 'UNTAR');
INSERT INTO contestant (name_code, name, school) VALUES ('sql-02', 'Azure Dragon 77', 'UNTAR');
INSERT INTO contestant (name_code, name, school) VALUES ('sql-03', 'TeamTam', 'NUS');
INSERT INTO contestant (name_code, name, school) VALUES ('sql-04', 'NightRain', 'UNTAR');
INSERT INTO contestant (name_code, name, school) VALUES ('sql-05', 'Awrakin', 'UI');
INSERT INTO contestant (name_code, name, school) VALUES ('sql-06', 'Ainge WF', 'ITB');

INSERT INTO login (username, password, name_code) VALUES ('sqluntar001', 'asd12', 'sql-001');

INSERT INTO totalscore (name_code, score) VALUES('sql-01', 100);
INSERT INTO totalscore (name_code, score) VALUES('sql-02', 90);
INSERT INTO totalscore (name_code, score) VALUES('sql-03', 80);
INSERT INTO totalscore (name_code, score) VALUES('sql-04', 70);
INSERT INTO totalscore (name_code, score) VALUES('sql-05', 60);
INSERT INTO totalscore (name_code, score) VALUES('sql-06', 50);

INSERT INTO PROBLEM (PROB_NUM, SOLUTION_QUERY) VALUES ('1', "SELECT ID_PESERTA AS 'ID', NAMA AS 'NAMA PESERTA' FROM PESERTA WHERE NAMA LIKE 'B%' OR NAMA LIKE '%S';");
INSERT INTO PROBLEM (PROB_NUM, SOLUTION_QUERY) VALUES ('2', "SELECT M.MATA_PELAJARAN AS 'MATA PELAJARAN', G.JURUSAN AS 'JURUSAN' FROM PELAJARAN M, PENGAJAR G, KELAS K WHERE K.ID_PENGAJAR = G.ID_PENGAJAR AND K.KODE_P = M.KODE_P AND G.NAMA = 'KIM';");
INSERT INTO PROBLEM (PROB_NUM, SOLUTION_QUERY) VALUES ('3', "SELECT P.NAMA ||' BELUM MEMILIKI HURUF MUTU' AS 'INFORMASI' FROM PESERTA P, NILAI N WHERE N.HURUF_MUTU IS NULL AND P.ID_PESERTA = N.ID_PESERTA;");
INSERT INTO PROBLEM (PROB_NUM, SOLUTION_QUERY) VALUES ('4', "SELECT NAMA, HONOR AS 'HONOR SEBELUM DIPOTONG PPH 5%', HONOR * 0.05 AS 'PPH', HONOR - (HONOR * 0.05) AS 'HONOR YANG DITERIMA' FROM PENGAJAR ORDER BY HONOR ASC;");
INSERT INTO PROBLEM (PROB_NUM, SOLUTION_QUERY) VALUES ('5', "SELECT JURUSAN AS 'JURUSAN', MIN(HONOR) AS 'HONOR TERKECIL', AVG(HONOR) AS 'HONOR RATA-RATA', MAX(HONOR) AS 'HONOR TERBESAR' FROM PENGAJAR GROUP BY JURUSAN;");
INSERT INTO PROBLEM (PROB_NUM, SOLUTION_QUERY) VALUES ('6', "SELECT P.NAMA AS 'NAMA PENGAJAR', M.MATA_PELAJARAN AS 'MATA PELAJARAN', M.JURUSAN AS 'JURUSAN' FROM PELAJARAN M, PENGAJAR P, KELAS K WHERE K.ID_PENGAJAR = P.ID_PENGAJAR AND K.KODE_P = M.KODE_P AND K.TAHUN = '2015' AND K.SEMESTER = 'GENAP';");
INSERT INTO PROBLEM (PROB_NUM, SOLUTION_QUERY) VALUES ('7', "SELECT P.NAMA AS 'NAMA PENGAJAR', COUNT(K.KODE_P) AS 'JUMLAH KELAS' FROM PENGAJAR P, KELAS K WHERE P.ID_PENGAJAR = K.ID_PENGAJAR AND TAHUN = '2014' GROUP BY P.NAMA;');
INSERT INTO PROBLEM (PROB_NUM, SOLUTION_QUERY) VALUES ('8', "SELECT S.NAMA AS 'NAMA PESERTA', P.MATA_PELAJARAN AS 'MATA PELAJARAN', N.HURUF_MUTU AS 'NILAI MUTU' FROM PESERTA S, PELAJARAN P, NILAI N WHERE N.ID_PESERTA = S.ID_PESERTA AND N.KODE_P = P.KODE_P AND N.TAHUN = '2015' AND SEMESTER = 'GENAP' ORDER BY S.NAMA ASC;");
INSERT INTO PROBLEM (PROB_NUM, SOLUTION_QUERY) VALUES ('9', "SELECT GEDUNG AS 'GEDUNG', COUNT(RUANG) AS 'INTENSITAS PEMAKAIAN GEDUNG' FROM JADWAL WHERE SEMESTER ='GENAP' GROUP BY GEDUNG;");
INSERT INTO PROBLEM (PROB_NUM, SOLUTION_QUERY) VALUES ('10', "SELECT NAMA AS 'NAMA PENGAJAR', JURUSAN AS 'JURUSAN', HONOR AS 'HONOR' FROM PENGAJAR WHERE HONOR > (SELECT AVG(HONOR) FROM PENGAJAR);");


SELECT c.name_code, c.name, c.school, t.score FROM contestant c, totalscore t WHERE c.name_code = t.name_code ORDER BY t.score DESC;
commit;

-- INIT AWAL DATABASE --
CREATE SMALLFILE TABLESPACE users datafile '/u01/app/oracle/oradata/ORCL/users,.dbf' size 10g;
ALTER DATABASE default TABLESPACE users;
CREATE ROLE peserta;
GRANT CREATE SESSION, CONNECT ,CREATE TABLE TO peserta;

-- UNTUK IMPORT / CREATE PESERTA BARU --
CREATE USER leo IDENTIFIED BY leo123;
GRANT peserta TO sqluntar001;
ALTER user leo quota 50m on users;
-- --------------------------------- --

DROP USER kampret;
CREATE USER kampret IDENTIFIED by "666kg";
CREATE USER ;

SELECT * FROM login;
SELECT * FROM contestant;
TRUNCATE TABLE contestant;
TRUNCATE TABLE totalscore;
DELETE FROM contestant;

-- DROPPING TABLE --
DROP TABLE totalscore;
DROP TABLE login;
DROP TABLE submission;
DROP TABLE problem;
DROP TABLE contestant;

CREATE USER sqluntar001 IDENTIFIED BY "4190a";